### ISSUE TITLE
JavaScript Error when running bitcar --setup

### ISSUE THREAD

**Issue by tomwolber** [carsdotcom/bitcar#3]
On Mac OS Sierra, tried installing and setting up bitcar

```
tommy@tommy ~/dev
🍔   npm i -g bitcar
/usr/local/bin/bitcar -> /usr/local/lib/node_modules/bitcar/index.js
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-package-arg requires hosted-git-info@'^2.1.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/hosted-git-info,
npm WARN unmet dependency which is version 2.1.4
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client requires graceful-fs@'^4.1.6' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 4.1.4
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/rimraf requires glob@'^7.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/glob,
npm WARN unmet dependency which is version 7.0.4
bitcar@1.5.4 /usr/local/lib/node_modules/bitcar
├── open@0.0.5
├── omelette@0.3.2
├── minimist@1.2.0
├── rc@1.1.7 (ini@1.3.4, strip-json-comments@2.0.1, deep-extend@0.4.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── simple-git@1.67.0
├── bluebird@3.5.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── readdirp@2.1.0 (set-immediate-shim@1.0.1, graceful-fs@4.1.11, minimatch@3.0.3, readable-stream@2.2.3)
├── mem-fs@1.1.3 (vinyl@1.2.0, through2@2.0.3, vinyl-file@2.0.0)
├── mem-fs-editor@3.0.2 (deep-extend@0.4.1, commondir@1.0.1, rimraf@2.6.1, globby@6.1.0, vinyl@2.0.1, through2@2.0.3, multimatch@2.1.0, glob@7.1.1, ejs@2.5.6)
├── axios@0.15.3 (follow-redirects@1.0.0)
├── inquirer@3.0.6 (ansi-escapes@1.4.0, through@2.3.8, cli-width@2.1.0, strip-ansi@3.0.1, mute-stream@0.0.7, figures@2.0.0, string-width@2.0.0, run-async@2.3.0, external-editor@2.0.1, cli-cursor@2.1.0, rx@4.1.0)
└── lodash@4.17.4


tommy@tommy ~/dev
🍔   bitcar --setup
/usr/local/lib/node_modules/bitcar/cli.js:38
        let { results, confirmMessage, errorMessage, handler } = options;
            ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/bitcar/index.js:5:13
    at Object.<anonymous> (/usr/local/lib/node_modules/bitcar/index.js:16:2)
    at Module._compile (module.js:409:26)


```

**Comment by tomwolber** [comment]
update: i'm on node 4.6 for reasons related to the crusty enterprise environment I have at work, once I switched to node 7.7.2, it works fine.

**Comment by machellerogden** [comment]
Thanks for checking it out! Appreciate the interest. Per README node 6 or higher is required.
